#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-SimplePlotter
version:      0.01
version_from: SimplePlotter.pm
installdirs:  site
requires:
    Wx:                            0.18
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
